library(dplyr)
library(future)
library(Seurat)

plan('cluster')
options(future.globals.maxSize= 5*1024^4, future.rng.onMisuse="ignore")
setwd('~/scratch60/pem/')

ldat <- readRDS('ldat1.rds')
anchorFeats <- SelectIntegrationFeatures(ldat,nfeatures=3000)
saveRDS(anchorFeats,'anchorFeats.rds')
ldat <- PrepSCTIntegration(ldat,anchor.features=anchorFeats)
saveRDS(ldat,'ldat1.1.rds')

ldat <- readRDS('ldat1.1.rds')
anchorFeats <- readRDS('anchorFeats.rds')
ldat <- purrr::map(ldat,~RunPCA(.x,features=anchorFeats))
anchorNames <- FindIntegrationAnchors(ldat,anchor.features=anchorFeats,normalization.method='SCT',reduction='rpca')
rm(anchorFeats)
saveRDS(anchorNames,'anchorNames.rds')

ldat <- IntegrateData(anchorNames,normalization.method='SCT')
saveRDS(ldat,'ldat2.rds')
rm(anchorNames)

ldat <- RunPCA(ldat,npcs=50)
saveRDS(ldat,'ldat2.1.rds')
png('elbows50.png',1000,600,'px')
ElbowPlot(ldat,ndims=50)
dev.off()
png('elbows25.png',1000,600,'px')
ElbowPlot(ldat,ndims=25)
dev.off()
ldat <- readRDS('ldat2.1.rds')
ldat <- FindNeighbors(ldat,dims=1:20)
saveRDS(ldat,'ldat3.rds')
ldat <- readRDS('ldat3.rds')
ldat <- FindClusters(ldat,resolution=0.9)
ldat <- RunUMAP(ldat,dims=1:20)
saveRDS(ldat,'ldat4.rds')
